#!/bin/sh

FPATH=/usr/bin/epitech-tests/tek2/piscine/$1

rm -rf /tmp/epitech-tests;
mkdir /tmp/epitech-tests && mkdir /tmp/epitech-tests/srcs &&
cp -r ./ /tmp/epitech-tests/srcs &&
cp -r $FPATH/ /tmp/epitech-tests &&
nodeunit $FPATH/tests.js
